name 'eschiller-trac'
version '0.2.0'

author 'eschiller'
license 'Apache License, Version 2.0'
project_page 'https://www.github.com/eschiller/puppet-trac'
source ''
summary 'Puppet module for Trac'
description 'This module installs and manages Trac. Check README for details.'
dependency 'puppetlabs/apache', '>=1.0.1'
dependency 'puppetlabs/concat', '>=1.0.0'
dependency 'puppetlabs/firewall', '>=0.2.0'
dependency 'puppetlabs/postgresql', '>=3.2.0'
dependency 'puppetlabs/stdlib', '>=3.2.0'
dependency 'puppetlabs/vcsrepo', '>=0.1.2'
